language: python
cache: pip
python:
  - "3.6"
services:
  - "postgresql"
install:
  - "pip install -e ."
  - "pip install -r requirements-dev.txt"
  - "pip install coveralls pytest-cov"
script:
  - flake8 .
  - "py.test --ds=seed_auth_api.testsettings --cov=authapi --ignore='authapi/migrations' authapi"
after_success:
  - "coveralls"
deploy:
  provider: pypi
  user: praekelt.org
  password:
    secure: "NgFCtWL7GJm9qP5qGA1IYAW+ycPW9aDUsyIxCcmxGf4kANGD6eJG3qHgynZ/G0hZaXPvAX4/kbo6Jgw9mAc5LyrlNlBlhViaqeb3rxKZ5EcvlW6+9EmcMtTnW+7rxAYI/lF+YAkBT+MMy2WqQCEupDOtaezqbrpdNOmzN4DfujQSxgOjV8avqgh+jaONGxeyeShRMARLw/Q5gSxi4tNBLzl5w8h4C5pacdx+xsG4CkXo8idX+GxNt3J/zyJkWAzmM/YqaGaDFzf6ywQCm1dqQ/NrrYi/IArUm4Txr7ODtHLIBZQAVFBvK2wlLSeuXgR5NsQcgl7IQmPtQvyzaWQOVbXNRBD936J1t2ZK/ub7vQ9PJa+9+tl/wklH/8rhEulkJKDwCFNrAtQxqGBIQ9xl4Q5aXNmGoQNFRPa7LvZZT9bK58/pvQPM3f/d1zByarI7AmbilADKfU+dKXqOgQj+0Itm+aMeu30fS+lA6ERdiqnTx9iPKWIAeWgEtxD8wFdgkYyboClAeTjBNFnLrsDXZGMLWOQua9fa8lizyMyU6t6iiMi5dgWTootlAA8Jfc1vq17GFveeH/b8IMGtN9m6MptXp+lgPpZUqi3OzJhx5Vrd81AUIH7q5XZO5n5hSM40I9290VkAtPuPY7KnydZmmcBJFEzoaFFzKUt37NthCZc="
  distributions: sdist bdist_wheel
  on:
    tags: true
