language: python
cache: pip
python:
  - "3.6"
services:
  - "postgresql"
install:
  - "pip install -e ."
  - "pip install -r requirements-dev.txt"
  - "pip install coveralls pytest-cov"
script:
  - flake8 .
  - "py.test --ds=seed_auth_api.testsettings --cov=authapi --ignore='authapi/migrations' authapi"
after_success:
  - "coveralls"
deploy:
  provider: pypi
  user: praekelt.org
  password:
    secure: "gVA77IfkbTgSI/xaEP9My96CL5oGimr9k/dBhmUrhe4iq7CnNoHPyCpwVvQR2f8jqgfIM9jFE3CHdU2MEZLVEOoxgFGbD1rCKymTPJCRaIdvWdCdwRkVBUVmTMczWcxxqA6rGi0vpkmJcQICbfvt5tgTgQXL4aYQ8/0PJPhoUG1V23SNQo5vkQE5qVOYo1WfUjexLbS4zD4YMckjWMZYXUHJ8A7AmtP0CxfoTfF7MwqT4kHANKpblVc+j9M3Mn7uVveUmQHDgvNv0h2tmYO+T9kZgGDJ82JwBpckyKaMgCtVV4Cf39szivXMe8yTkLxh5zhCpwldiFttSwtVdPaFSfk3NMz2kL1NIngz4zRXdgYzIslSHUSqjYm9o35Z/jt/eEHDnhJYWjvwgpRRjRAkYfblnesiqgzvHkoTx8eYydkujJmirEanAmHANzvVPbmzUmNVbGh8CKKY5a1cPR5/QVgDnBQGItcw6hAQ018s1SGsQay3mpPgCvSL7VyQkM3M62D20IETXA4ROAgqKumhPOoG3r+V0+iL9+dMbimYyUdgzqAmuT65hLxJJaOpSALsfCTALZfb0I/fZLcRFhMj/9NnddIr5iT/e9KxLhPA3jSlJeC0JpQIV64wfUmtRaD5oawr5/lMB6HYXHwp8zJxZGDN130T+p9Qg3P/Kasnb98="
  distributions: sdist bdist_wheel
  on:
    tags: true
